# Generated by Django 2.1.7 on 2019-04-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190327_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
